### ISSUE TITLE
Migration branch

### ISSUE THREAD

**Issue by langest** [EzGaming/Switch2#5]
Migration did not open a pull request which would be preferable.
Could it be deleted or is it going to be used in the future?

**Comment by hidamaru** [comment]
I guess it can still be deleted, but how do you create a pull request towards another branch and not towards master?

**Comment by langest** [comment]
By pressing the green arrows that are circled to get to compare/create pull request/something more here.
Then compare the two branches and you will get an open pull request option.
But if you didn't merge it to master it should be fine anyway, but you should remove the branch if it isn't used anymore.
